"""create tickets table

Revision ID: 41b267f2d0fd
Revises: 
Create Date: 2025-09-12 16:27:59.901382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41b267f2d0fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('no_tiket', sa.String(length=64), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('keluhan', sa.Text(), nullable=True),
    sa.Column('teknisi', sa.String(length=255), nullable=True),
    sa.Column('indikasi', sa.String(length=255), nullable=True),
    sa.Column('tindakan', sa.String(length=255), nullable=True),
    sa.Column('before', sa.String(length=512), nullable=True),
    sa.Column('after', sa.String(length=512), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_no_tiket'), 'tickets', ['no_tiket'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nomer', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('extension', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('listeners',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nomer', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('nama', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('aktif', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('started_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('ended_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_listeners_nomer'), 'listeners', ['nomer'], unique=True)
    op.create_index(op.f('ix_listeners_id'), 'listeners', ['id'], unique=False)
    op.drop_index(op.f('ix_tickets_no_tiket'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
