"""create column id_user in ticket

Revision ID: ae4520d23e6c
Revises: d4e90a7af2ca
Create Date: 2025-09-22 18:26:30.033411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4520d23e6c'
down_revision: Union[str, Sequence[str], None] = 'd4e90a7af2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('tickets', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'user_id')
    
    # ### end Alembic commands ###
