"""cek

Revision ID: dc149c337d3d
Revises: 41b267f2d0fd
Create Date: 2025-09-12 18:27:45.470169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc149c337d3d'
down_revision: Union[str, Sequence[str], None] = '41b267f2d0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'nomer',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('files', 'nama',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('files', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('files', 'url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('files', 'extension',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('files', 'location',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.alter_column('listeners', 'nama',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listeners', 'nama',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.alter_column('files', 'location',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=True)
    op.alter_column('files', 'extension',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('files', 'url',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('files', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('files', 'nama',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('files', 'nomer',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
