"""add lokasi koordinat column to tickets

Revision ID: ff4f2f95bfce
Revises: dc149c337d3d
Create Date: 2025-09-14 21:28:29.988099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4f2f95bfce'
down_revision: Union[str, Sequence[str], None] = 'dc149c337d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('lokasi_koordinat', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'lokasi_koordinat')
    # ### end Alembic commands ###
